name: linuxday_2023_presentation
description: Presentation for the Linux Day 2023 at Università Milano Bicocca
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_deck: ^0.8.0
  google_fonts: ^6.1.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.1
  wolt_modal_sheet: ^0.1.4

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/platforms/
    - assets/images/social-icons/
    - assets/images/ubuntu-desktop/
    - assets/gifs/
    - assets/videos/
    - assets/me/
