name: linuxday_2023_presentation
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_deck: ^0.5.0
  qr_flutter: ^4.1.0

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/platforms/
    - assets/images/social-icons/
    - assets/images/ubuntu-desktop/
    - assets/gifs/
